---
key_path: license_expires_at
description: The date the license ends
product_section: growth
product_stage: growth
product_group: group::product intelligence
product_category: collection
value_type: string
status: data_available
time_frame: none
data_source: system
distribution:
- ee
tier:
- premium
- ultimate
skip_validation: true
