---
key_path: usage_activity_by_stage.secure.user_license_management_jobs
description: no idea, Count of License Scanning jobs run, it implies user but AFAIK
  we don't track per user
product_section: sec
product_stage: secure
product_group: group::composition analysis
product_category: license_compliance
value_type: string
status: data_available
time_frame: none
data_source:
distribution:
- ee
tier:
- ultimate
skip_validation: true
