---
key_path: licensee.Name
description: Name on the GitLab license
product_section: fulfillment
product_stage: fulfillment
product_group: group::license
product_category: license
value_type: string
status: data_available
time_frame: none
data_source: license
data_category: Subscription
distribution:
- ee
tier:
- premium
- ultimate
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/557
