---
name: ci_require_credit_card_for_old_users
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61565 
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/330706
milestone: '13.12'
type: development
group: group::continuous integration
default_enabled: false
