---
name: credential_inventory_gpg_keys
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49835
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/292961
milestone: '13.8'
type: development
group: group::compliance
default_enabled: false
