---
name: fetch_mirror_check_tags_changed
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49629
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/292602
milestone: '13.8'
type: development
group: group::source code
default_enabled: false
