---
name: geo_lfs_object_replication
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/56286
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/329697
milestone: '13.11'
type: development
group: group::geo
default_enabled: true
