---
name: geo_group_wiki_repository_replication
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54914
rollout_issue_url:
milestone: '13.10'
type: development
group: group::geo
default_enabled: true
