---
name: geo_terraform_state_replication
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/36594
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/254623
group: group::geo
type: development
default_enabled: false
