---
name: iteration_charts
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/41280
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/229046
milestone: '13.4'
type: development
group: group::project management
default_enabled: false
