---
name: new_issues_analytics_chart_data
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46444
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/247271
milestone: '13.6'
type: development
group: group::optimize
default_enabled: false
