---
name: secure_vulnerability_autofix_indicator
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/48251/
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/288347
milestone: '13.7'
type: development
group: group::composition analysis
default_enabled: true
