---
name: vulnerability_history
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/27052
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/213625
group: "group::threat insights"
type: development
default_enabled: true
