---
# Name of this metric contains g_project_management prefix
# because we are using the same slot from issue_tracking to
# allow data aggregation.
key_path: g_project_management_epic_title_changed_monthly
description: Counts of MAU changing epic titles
product_section: dev
product_stage: plan
product_group: group:product planning
product_category: epics_usage
value_type: number
status: implemented
milestone: "13.10"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/56489
time_frame: 28d
data_source: redis_hll
distribution:
- ee
 tier:
 - premium
 - ultimate
