---
# See Usage Ping metrics dictionary docs https://docs.gitlab.com/ee/development/usage_ping/metrics_dictionary.html
key_path: redis_hll_counters.analytics.i_analytics_dev_ops_adoption_monthly
description: Counts visits to DevOps Adoption page per month
product_section: dev
product_stage: manage
product_group: group::optimize
product_category: devops_reports
value_type: number
status: implemented
milestone: "13.11"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57104
time_frame: 28d
data_source: redis_hll
distribution:
  - ee
tier:
  - premium
  - ultimate
