---
key_path: usage_activity_by_stage_monthly.create.merge_requests_with_optional_codeowners
description:
product_section: dev
product_stage: create
product_group: group::code review
product_category: source_code_management
value_type: number
status: data_available
time_frame: 28d
data_source:
distribution:
- ee
tier: []
skip_validation: true
