---
key_path: usage_activity_by_stage_monthly.secure.user_secret_detection_scans
description: Number of users who have run a Secret Detection scan
product_section: sec
product_stage: secure
product_group: group::static analysis
product_category: secret_detection
value_type: number
status: data_available
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49444
time_frame: 28d
data_source: database
data_category: Operational
distribution:
  - ee
tier:
  - ultimate
