---
key_path: usage_activity_by_stage_monthly.create.users_using_lfs_locks
description: Number of users that have used default branch locks through the UI
product_section: dev
product_stage: create
product_group: group::source code
product_category: source_code_management
value_type: number
status: data_available
time_frame: 28d
data_source:
distribution:
- ee
tier: []
skip_validation: true
