---
key_path: redis_hll_counters.ide_edit.g_edit_by_sfe_weekly
description:
product_section: dev
product_stage: create
product_group: group::editor
product_category:
value_type: number
status: data_available
time_frame: 7d
data_source: redis_hll
distribution:
- ee
tier: []
skip_validation: true
