cloud-native-image:
  image: ruby:2.6-alpine
  dependencies: []
  stage: post-test
  allow_failure: true
  variables:
    GIT_DEPTH: "1"
  rules:
    - <<: *if-canonical-dot-com-tag
      when: manual
  script:
    - install_gitlab_gem
    - CNG_PROJECT_PATH="gitlab-org/build/CNG" BUILD_TRIGGER_TOKEN=$CI_JOB_TOKEN ./scripts/trigger-build cng
