---
data_category: Optional
key_path: counts.status_page_projects
description: Projects with status page enabled
product_section: ops
product_stage: monitor
product_group: group::monitor
product_category: incident_management
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ee
tier:
- ultimate
