---
data_category: Optional
key_path: counts.license_management_jobs
description: Count of License Scanning jobs run
product_section: sec
product_stage: secure
product_group: group::composition analysis
product_category: license_compliance
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ee
tier:
- ultimate
