key_path: counts.geo_nodes
description: Total number of sites in a Geo deployment
value_type: integer
product_category: disaster_recovery
stage: enablement
status: data_available
milestone: 11.2
group: 'group::geo'
time_frame: all
data_source: database
distribution: [ee]
tier: ['premium', 'ultimate']
